menu/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [

    # MENU PRINCIPAL

    # index
    url(r'^$', login_required(views.index), name='home'),

    # login
    url(r'^login/$', LoginView.as_view(), name='login'),

    # login
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),

    # ELEMENTOS

    # Agregar un elemento

    url(r'^agregarElemento/$', login_required(views.ElementoCreate.as_view(success_url="/menu/")),
        name='agregarElemento'),

    # Lista para modificar elementos

    url(r'^modElemento/$', login_required(views.detalleElemento.as_view(
    )), name='modElemento'),

    # Actualizar elemento

    url(r'^actualizarElemento/(?P<pk>[0-9]+)/$', login_required(views.ElementoUpdate.as_view(
        success_url="/menu/modElemento/")), name='actualizarElemento'),

    # Borrar elemento

    url(r'^actualizarElemento/(?P<pk>[0-9]+)/borrar$', login_required(views.ElementoDelete.as_view(
    )), name='borrarElemento'),

    # Lista sola de elementos

    url(r'^listaElemento/$', login_required(views.listaElementos.as_view()), name='listaElementos'),

    # UNIDADES DE MEDIDA

    # Agregar unidad

    url(r'^agregarUnidadMedida/$', login_required(views.UnidadMedidaCreate.as_view(success_url="/menu/")),
        name='agregarUnidadMedida'),

    # Actualizar unidad

    url(r'^actualizarUnidadMedida/(?P<pk>[0-9]+)/$', login_required(views.UnidadMedidaUpdate.as_view(
        success_url="/menu/modUnidadMedida/")), name='actualizarUnidadMedida'),

    # Lista de unidades para modificar

    url(r'^modUnidadMedida/$', login_required(views.detalleUnidadMedida.as_view(
    )), name='modUnidadMedida'),

    # Borrar una unidad

    url(r'^borrarUnidadMedida/(?P<pk>[0-9]+)/borrar$', login_required(views.UnidadMedidaDelete.as_view(
    )), name='borrarUnidadMedida'),

    # PRODUCTOS

    # Agregar un producto

    url(r'^agregarProducto/$', login_required(views.ProductoInventarioCreate.as_view(success_url="/menu/")),
        name='agregarProducto'),

    # Lista de productos para modificar

    url(r'^modProducto/$', login_required(views.detalleProducto.as_view(
    )), name='modProducto'),

    # Actualizar un producto

    url(r'^actualizarProducto/(?P<pk>[0-9]+)/$', login_required(views.ProductoInventarioUpdate.as_view(
        success_url="/menu/modProducto/")), name='actualizarProducto'),

    # Borrar un producto

    url(r'^actualizarProducto/(?P<pk>[0-9]+)/borrar$', login_required(views.ProductoDelete.as_view(
    )), name='borrarProducto'),

    # ORDENES

    # Agregar una orden

    url(r'^agregarOrden/$', login_required(views.OrdenProductoCreate.as_view()),
        name='agregarElemento'),

    # Actualizar Orden

    url(r'^actualizarOrden/(?P<pk>[0-9]+)/$', login_required(views.OrdenProductoUpdate.as_view(
        success_url="/menu/modOrden/")), name='actualizarOrden'),

    # Borrar Orden

    url(r'^actualizarOrden/(?P<pk>[0-9]+)/borrar$', login_required(views.OrdenDelete.as_view(
        success_url="/menu/modOrden/")), name='borrarOrden'),

    # Facturacion

    url(r'^facturar/(?P<pk>[0-9]+)/$', login_required(views.OrdenUpdateF.as_view()), name='facturar'),

    # Lista de ordenes para modificar

    url(r'^modOrden/$', login_required(views.detalleOrden.as_view(
    )), name='modOrden'),

    # Lista de facturas a modificar

    url(r'^modFactura/$', login_required(views.modFactura.as_view(
    )), name='modFactura'),

    # TIPO DE CAMBIO

    # Modificar tipo de cambio

    url(r'^tipoCambio/(?P<pk>[0-9]+)/$', login_required(views.TipoCambioCreate.as_view(success_url="/menu/")),
        name='modFactura'),

    # USUARIOS

    # Crear usuario
    url(r'^crearUsuario/$', login_required(views.SignUp.as_view(success_url="/menu/")),
        name='crearUsuario'),

    # Editar usuario actual
    url(r'^actualizarUsuario/(?P<pk>[0-9]+)/$', login_required(views.ModificarUsuario.as_view(success_url="/menu/")),
        name='actualizarUsuario'),

    # Lista de usuarios a modificar

    url(r'^actualizarUsuario/$', login_required(views.ActualizarUsuario.as_view(
    )), name='modUsuario'),

    # Borrar usuario

    url(r'^borrarUsuario/(?P<pk>[0-9]+)/borrar$', login_required(views.UsuarioDelete.as_view(
    )), name='borrarUsuario'),

    # Descuentos

    # Agregar un Descuento

    url(r'^agregarDescuento/$', login_required(views.DescuentoCreate.as_view(success_url="/menu/")),
        name='agregarDescuento'),

    # Modificar un Descuento

    url(r'^actualizarDescuento/(?P<pk>[0-9]+)/$', login_required(views.DescuentoUpdate.as_view(success_url="/menu/")),
        name='actualizarDescuento'),

    # Lista de Descuento
    url(r'^listaDescuento/$', login_required(views.listaDescuento.as_view(
    )), name='listaDescuento'),

    # Borrar Descuento

    url(r'^actualizarDescuento/(?P<pk>[0-9]+)/borrar$', login_required(views.DescuentoDelete.as_view(
        success_url="/menu/")), name='borrarDescuento'),

]

menu/models.py
from datetime import datetime
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone

from Inventario import settings


class UnidadMedida(models.Model):
    nombre = models.CharField(max_length=500)
    sigla = models.CharField(max_length=500)

    def __str__(self):
        return self.nombre


class Inventario(models.Model):
    nombre = models.CharField(max_length=500)
    cantidad = models.IntegerField()
    unidadMedida = models.ForeignKey(UnidadMedida, on_delete=models.CASCADE, default=None)
    valorCompra = models.BigIntegerField(default=None, blank=True, null=True)
    valorVenta = models.BigIntegerField(default=None, blank=True, null=True)

    def __str__(self):
        return self.nombre


class TipoPago(models.Model):
    nombre = models.CharField(max_length=500)

    def __str__(self):
        return self.nombre


class TipoOrden(models.Model):
    nombre = models.CharField(max_length=500)

    def __str__(self):
        return self.nombre


class Moneda(models.Model):
    nombre = models.CharField(max_length=500)
    siglas = models.CharField(max_length=500)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    class Meta:
        ordering = ['nombre']

    nombre = models.CharField(max_length=500)
    valor = models.BigIntegerField(default=None, blank=True, null=True)

    def __str__(self):
        return self.nombre


class Descuento(models.Model):
    class Meta:
        ordering = ['valor']

    valor = models.IntegerField()

    def __str__(self):
        return str(self.valor)


class Orden(models.Model):
    fecha = models.DateField(default=timezone.now)
    pagadores = models.IntegerField()
    tipoOrden = models.ForeignKey(TipoOrden, on_delete=models.CASCADE)
    tipoPago = models.ForeignKey(TipoPago, on_delete=models.CASCADE)
    cliente = models.CharField(max_length=500)
    productosExtra = models.ManyToManyField(Producto, through='CantidadesProductos', blank=True)
    notas = models.CharField(max_length=1000, default=None, blank=True, null=True)
    precioFinal = models.BigIntegerField()
    facturado = models.BooleanField(default=False)
    numero = models.BigIntegerField(default=0)
    descuento = models.ForeignKey(Descuento, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.pk)


class CantidadesProductos(models.Model):
    orden = models.ForeignKey(Orden, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.BigIntegerField(default=0)


class CantidadesInventario(models.Model):
    inventario = models.ForeignKey(Inventario, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.BigIntegerField(default=0)


class CantidadesSelf(models.Model):
    productoSelf = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name="elemento")
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name="lista")
    cantidad = models.BigIntegerField(default=0)


class TipoCambio(models.Model):
    valor = models.IntegerField()

    def __str__(self):
        return self.valor


class CustomUser(AbstractUser):
    class Meta:
        permissions = (
            ("can_inventory", "Puede Ver Inventario"),
            ("can_products", "Puede Ver Productos"),
            ("can_orders", "Puede Ver Ordenes"),
            ("can_reports", "Puede Ver Reportes"),
            ("can_discounts", "Puede Ver Descuentos"),

            #Funciones especificas

                # User
            ("is_agent", "Puede Crear cajeros"),
                # Inventario
            ("can_create_element", "Puede Crear Elemento"),
            ("can_mod_element", "Puede Modificar Elemento"),
            ("can_create_unit", "Puede Crear Unidad de Medida"),
            ("can_mod_unit", "Puede Modificar Unidad de Medida"),
                # Productos
            ("can_create_product", "Puede Crear Producto"),
            ("can_mod_product", "Puede Modificar Producto"),
                # Orden
            ("can_create_order", "Puede Crear Orden"),
            ("can_invoices", "Puede Entrar a facturas"),
            ("can_frozen_order", "Puede Entrar a Ordenes Abiertas"),
            ("can_mod_exchange", "Puede Modificar Tipo de Cambio"),
                # Descuento
            ("can_create_discount", "Puede Crear Descuento"),
            ("can_mod_discount", "Puede Modificar Descuento"),
        )

    direct_boss = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="rdirect_boss", unique=False, blank=True,
                                    null=True, db_index=True)
    indirect_boss = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="rindirect_boss", unique=False, blank=True,
                                      null=True,
                                      db_index=True)
    creator_boss = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="rcreator_boss", unique=False, blank=True,
                                     null=True,
                                     db_index=True)

menu/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User, Group
from django.forms import inlineformset_factory

from menu.models import Inventario, UnidadMedida, Producto, Orden, TipoOrden, Moneda, TipoPago, \
    Descuento, CantidadesProductos, CantidadesInventario, CantidadesSelf, CustomUser
from django import forms
from django.utils.translation import ugettext_lazy as _


class UnidadMedidaForm(forms.ModelForm):
    class Meta:
        model = UnidadMedida
        fields = ['nombre', 'sigla']
        widgets = {
            'nombre': forms.TextInput(attrs={'style': 'background: #c2c0c0', 'class': 'form-control'}),
            'sigla': forms.TextInput(attrs={'style': 'background: #c2c0c0', 'class': 'form-control'})

        }


class InventarioForm(forms.ModelForm):
    class Meta:
        model = Inventario
        fields = ['nombre', 'cantidad', 'unidadMedida', 'valorCompra', 'valorVenta']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'style': 'background: #c2c0c0'}),
            'cantidad': forms.TextInput(attrs={'class': 'form-control', 'style': 'background: #c2c0c0'}),
            'valorCompra': forms.NumberInput(attrs={'class': 'form-control', 'style': 'background: #c2c0c0'}),
            'valorVenta': forms.NumberInput(attrs={'class': 'form-control', 'style': 'background: #c2c0c0'})

        }
        unidadMedida = forms.ModelChoiceField(queryset=UnidadMedida.objects.all(),
                                              widget=forms.Select(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super(InventarioForm, self).__init__(*args, **kwargs)
        self.fields['unidadMedida'].empty_label = _("UNIT")
        self.fields['unidadMedida'].widget.choices = self.fields['unidadMedida'].choices


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'valor']
        widgets = {
            'nombre': forms.TextInput(attrs={'style': 'background: #c2c0c0', 'class': 'form-control'}),
            'valor': forms.NumberInput(attrs={'style': 'background: #c2c0c0', 'class': 'form-control'})
        }


class OrdenForm(forms.ModelForm):
    class Meta:
        model = Orden
        fields = ['cliente', 'tipoOrden', 'pagadores', 'tipoPago', 'notas',
                  'precioFinal', 'descuento', 'facturado']
        widgets = {
            'cliente': forms.TextInput(attrs={'style': 'background: #c2c0c0', 'class': 'form-control'}),
            'pagadores': forms.NumberInput(
                attrs={'style': 'background: #c2c0c0', 'class': 'form-control'}),
            'notas': forms.TextInput(attrs={'style': 'background: #c2c0c0', 'class': 'form-control'}),
            'precioFinal': forms.NumberInput(attrs={'style': 'background: #c2c0c0', 'class': 'form-control'}),
            'facturado': forms.CheckboxInput()
        }
        tipoOrden = forms.ModelChoiceField(queryset=TipoOrden.objects.all(),
                                           widget=forms.Select(attrs={'class': 'wrap-input100'}))
        descuento = forms.ModelChoiceField(queryset=Descuento.objects.all(),
                                           widget=forms.Select(attrs={'class': 'wrap-input100'}))
        tipoPago = forms.ModelChoiceField(queryset=TipoPago.objects.all())

    def __init__(self, *args, **kwargs):
        super(OrdenForm, self).__init__(*args, **kwargs)
        self.fields['descuento'].empty_label = "0"
        self.fields['descuento'].widget.choices = self.fields['descuento'].choices
        self.fields['tipoPago'].empty_label = _("PAYMENT")
        self.fields['tipoPago'].widget.choices = self.fields['tipoPago'].choices
        self.fields['tipoOrden'].empty_label = _("TYPE")
        self.fields['tipoOrden'].widget.choices = self.fields['tipoOrden'].choices


class CantidadesProductosForm(forms.ModelForm):
    class Meta:
        model = CantidadesProductos
        exclude = ()


CantidadesProductosFormSet = inlineformset_factory(Orden, CantidadesProductos, form=CantidadesProductosForm, extra=1)


class CantidadesInventarioForm(forms.ModelForm):
    class Meta:
        model = CantidadesInventario
        exclude = ()


CantidadesInventarioFormSet = inlineformset_factory(Producto, CantidadesInventario, form=CantidadesInventarioForm,
                                                    extra=1)


class CantidadesSelfForm(forms.ModelForm):
    class Meta:
        model = CantidadesSelf
        exclude = ()


CantidadesSelfFormSet = inlineformset_factory(Producto, CantidadesSelf, form=CantidadesSelfForm, fk_name="producto",
                                              extra=1)


class DescuentoForm(forms.ModelForm):
    class Meta:
        model = Descuento
        fields = ['valor']


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'direct_boss', 'indirect_boss', 'creator_boss')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'direct_boss', 'indirect_boss', 'creator_boss')


class UserGroupForm(forms.Form):
    CHOICES = [(group.name, group.name) for group in Group.objects.all()]
    name = forms.ChoiceField(choices=CHOICES, widget=forms.widgets.RadioSelect())

menu/templates/menu/base2.html
<!DOCTYPE html>
<html lang="es">

{% load staticfiles %}
{% load i18n %}
<!-- Begin Head -->
<head>
    <!-- Basic -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block titulo %}{% endblock %}</title>
    <meta name="keywords" content="HTML5 Theme"/>
    <meta name="description" content="Megakit - HTML5 Theme">
    <meta name="author" content="keenthemes.com">


    <!-- Web Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i|Montserrat:400,700" rel="stylesheet">



    {% block extrasHead %}
    {% endblock %}


    <style type="text/css">

        body.principal {
            background-image: url({% static 'menu/images/fondos/fondoPrincipal.jpeg' %})
        }

        body.orden {
            background-image: url({% static 'menu/images/fondos/fondoOrdenes.jpg' %})
        }

        colorOrden {
            cursor: pointer;
        }

    </style>


</head>
<!-- End Head -->

<!-- Body -->
<body class="principal">

{% block contenido %}



{% endblock %}

<script type="text/javascript" src="{% static "menu/vendor/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/vendor/jquery.migrate.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/vendor/jquery.smooth-scroll.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/vendor/jquery.back-to-top.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/vendor/scrollbar/jquery.scrollbar.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/vendor/magnific-popup/jquery.magnific-popup.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/vendor/swiper/swiper.jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/vendor/waypoint.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/vendor/counterup.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/vendor/cubeportfolio/js/jquery.cubeportfolio.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/vendor/jquery.parallax.min.js" %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsXUGTFS09pLVdsYEE9YrO2y4IAncAO2U"></script>
<script type="text/javascript" src="{% static "vendor/jquery.wow.min.js" %}"></script>

<!-- General Components and Settings -->
<script type="text/javascript" src="{% static "menu/js/global.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/js/components/header-sticky.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/js/components/scrollbar.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/js/components/magnific-popup.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/js/components/swiper.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/js/components/counter.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/js/components/portfolio-3-col.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/js/components/parallax.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/js/components/google-map.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/js/components/wow.min.js" %}"></script>
<script type="text/javascript" src="{% static "menu/js/main.js" %}"></script>
<!--========== END JAVASCRIPTS ==========-->

menu/templates/menu/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
</head>
<body>


<select class="asd" name="states[]" multiple="multiple">
  <option value="AL">Alabama</option>
  <option value="WY">Wyoming</option>
</select>



<script>
    $('.asd').select2();
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
</body>
</html>

menu/templates/menu/usuario_form.html
{% extends 'menu/base.html' %}
{% load staticfiles %}
{% block titulo %}
    Nuevos Ingredientes
{% endblock %}
{% block extrasHead %}

    {{ form.media.css }}
    <link rel="icon" type="image/png" href="{% static 'formulario/images/icons/favicon.ico' %}  "/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'formulario/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'formulario/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'formulario/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'formulario/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'formulario/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'formulario/vendor/animsition/css/animsition.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href={% static 'formulario/"vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel=" stylesheet" type="text/css" href="{% static 'formulario/vendor/daterangepicker/daterangepicker.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'formulario/css/cssContact.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'formulario/css/utilContact.css' %}">
    <!--===============================================================================================-->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <style>
        .btn {
            display: inline-block;
            padding: 9px 12px;
            padding-top: 7px;
            margin-bottom: 0;
            font-size: 14px;
            line-height: 20px;
            color: #5e5e5e;
            text-align: center;
            vertical-align: middle;
            cursor: pointer;
            background-color: #d1dade;
            -webkit-border-radius: 3px;
            -webkit-border-radius: 3px;
            -webkit-border-radius: 3px;
            background-image: none !important;
            border: none;
            text-shadow: none;
            box-shadow: none;
            transition: all 0.12s linear 0s !important;
            font: 14px/20px "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

        .btn-cons {
            margin-right: 5px;
            min-width: 120px;
            margin-bottom: 8px;
        }

        .btn-save {
            color: #fff;
            background-color: #008891;
            border-color: #46b8da;
        }

        #id_indirect_boss {
            display: none;

        }

        #id_direct_boss {
            display: none;

        }

        #id_creator_boss {
            display: none;
        }

        li {
            color: red;
            font-size: 1em;
        }

        input {
            background: #c2c0c0;
            width: 100%;
        }

        select{
            background: #c2c0c0;
            height:34px;
            border: none;
            border-radius: 4px;
            color: #1e4652;
            font: Gill Sans MT;

        }
    </style>
{% endblock %}
{% block contenido %}
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container-contact101">
            <div class="wrap-contact101">
                <span class="contact100-form-title">
                    CREAR NUEVO CAJERO
                </span>
            </div>
        </div>
        <div class="container-contact100">
            <div class="wrap-contact100">
                <form class="contact100-form validate-form">
                    {% csrf_token %}
                    <span class="forms-title">NOMBRE DE USUARIO</span><br>
                    <div class="form-control" style="background: #c2c0c0;">
                        {{ form.username }}
                    </div>
                    <br>

                    <span class="forms-title">CONTRASEÑA</span><br>
                    <div class="form-control" style="background: #c2c0c0;">
                        {{ form.password1 }}
                    </div>
                    <br>
                    <span class="forms-title">CONFIRMAR CONTRASEÑA</span><br>
                    <div class="form-control" style="background: #c2c0c0;">
                        {{ form.password2 }}
                    </div>
                    <br>
                    <span class="forms-title">TIPO DE PERFIL</span><br>
                    <select name="selectGrupos">
                        {% for grupos in lista_grupos %}
                            <option value="{{ grupos.name }}">{{ grupos.name }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    {{ form.direct_boss }}
                    {{ form.indirect_boss }}
                    {{ form.creator_boss }}


                    {{ form.errors }}
                    <br>


                    <button type="submit" class="btn btn-save btn-cons ">GUARDAR</button>
                </form>
            </div>
        </div>
    </form>

    <script type="application/javascript">

        $(window).load(function () {
            $('#id_direct_boss').val(1);
            $('#id_creator_boss').val(1);
        });

        $(document).ready(function () {
            $('form').fadeIn(800);
        });
        $(".fadeOut").click(function () {
            $("form").fadeOut(1000, function () {
                window.location.href = "/menu/"
            })
        });
    </script>
    <script>  {{ form.media.js }} </script>


    <!--===============================================================================================-->
    <script src="{% static 'formulario/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'formulario/vendor/animsition/js/animsition.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'formulario/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'formulario/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'formulario/vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'formulario/vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'formulario/vendor/daterangepicker/daterangepicker.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'formulario/vendor/countdowntime/countdowntime.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'formulario/js/main.js' %}"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-23581568-13');

    </script>

{% endblock %}